<a href="https://colab.research.google.com/github/AkshayK25/GoOgle-ColAbOratories/blob/master/Movie_Analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [0]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
movies = pd.read_csv("https://raw.githubusercontent.com/AkshayK25/GoOgle-ColAbOratories/master/Movie%2BAssignment%2BData.csv")
# Write your code for importing the csv file here
movies

                 color       director_name  ...  aspect_ratio  movie_facebook_likes
0                Color       James Cameron  ...          1.78                 33000
1                Color      Gore Verbinski  ...          2.35                     0
2                Color          Sam Mendes  ...          2.35                 85000
3                Color   Christopher Nolan  ...          2.35                164000
4                  NaN         Doug Walker  ...           NaN                     0
5                Color      Andrew Stanton  ...          2.35                 24000
6                Color           Sam Raimi  ...          2.35                     0
7                Color        Nathan Greno  ...          1.85                 29000
8                Color         Joss Whedon  ...          2.35                118000
9                Color         David Yates  ...          2.35                 10000
10               Color         Zack Snyder  ...          2.35                197000
11               Color        Bryan Singer  ...          2.35                     0
12               Color        Marc Forster  ...          2.35                     0
13               Color      Gore Verbinski  ...          2.35                  5000
14               Color      Gore Verbinski  ...          2.35                 48000
15               Color         Zack Snyder  ...          2.35                118000
16               Color      Andrew Adamson  ...          2.35                     0
17               Color         Joss Whedon  ...          1.85                123000
18               Color        Rob Marshall  ...          2.35                 58000
19               Color    Barry Sonnenfeld  ...          1.85                 40000
20               Color       Peter Jackson  ...          2.35                 65000
21               Color           Marc Webb  ...          2.35                 56000
22               Color        Ridley Scott  ...          2.35                 17000
23               Color       Peter Jackson  ...          2.35                 83000
24               Color         Chris Weitz  ...          2.35                     0
25               Color       Peter Jackson  ...          2.35                     0
26               Color       James Cameron  ...          2.35                 26000
27               Color       Anthony Russo  ...          2.35                 72000
28               Color          Peter Berg  ...          2.35                 44000
29               Color     Colin Trevorrow  ...          2.00                150000
...                ...                 ...  ...           ...                   ...
5013             Color          Eric Eason  ...          1.78                    61
5014             Color            Uwe Boll  ...          2.35                     0
5015   Black and White   Richard Linklater  ...          1.37                  2000
5016             Color     Joseph Mazzella  ...           NaN                    33
5017             Color        Travis Legge  ...          1.78                   200
5018             Color       Alex Kendrick  ...          1.85                   725
5019             Color       Marcus Nispel  ...          1.85                     0
5020               NaN     Brandon Landers  ...           NaN                    33
5021             Color         Jay Duplass  ...           NaN                   297
5022   Black and White          Jim Chuchu  ...           NaN                    45
5023             Color          Daryl Wein  ...          2.35                   324
5024             Color         Jason Trost  ...          2.35                   835
5025             Color         John Waters  ...          1.37                     0
5026             Color     Olivier Assayas  ...          2.35                   171
5027             Color        Jafar Panahi  ...          1.85                   697
5028   Black and White       Ivan Kavanagh  ...          1.33                   105
5029             Color    Kiyoshi Kurosawa  ...          1.85                   817
5030             Color        Tadeo Garcia  ...           NaN                    22
5031             Color  Thomas L. Phillips  ...         16.00                   424
5032             Color     Ash Baron-Cohen  ...           NaN                    20
5033             Color       Shane Carruth  ...          1.85                 19000
5034             Color    Neill Dela Llana  ...           NaN                    74
5035             Color    Robert Rodriguez  ...          1.37                     0
5036             Color     Anthony Vallone  ...           NaN                     4
5037             Color        Edward Burns  ...           NaN                   413
5038             Color         Scott Smith  ...           NaN                    84
5039             Color                 NaN  ...         16.00                 32000
5040             Color    Benjamin Roberds  ...           NaN                    16
5041             Color         Daniel Hsia  ...          2.35                   660
5042             Color            Jon Gunn  ...          1.85                   456

[5043 rows x 28 columns]

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
print(movies.head())
print(movies.columns)
print(movies.shape)
print(movies.dtypes)
length_initial_Rows = len(movies.index)
print(length_initial_Rows)

   color      director_name  ...  aspect_ratio  movie_facebook_likes
0  Color      James Cameron  ...          1.78                 33000
1  Color     Gore Verbinski  ...          2.35                     0
2  Color         Sam Mendes  ...          2.35                 85000
3  Color  Christopher Nolan  ...          2.35                164000
4    NaN        Doug Walker  ...           NaN                     0

[5 rows x 28 columns]
Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')
(5043, 28)
color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object
5043

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [5]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [6]:
# Write your code for row-wise null count here
movies.isnull().sum(axis = 1)

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [7]:
# Write your code for column-wise null percentages here
col_percent_null_values =(movies.isnull().sum()/len(movies))*100
round(col_percent_null_values,2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [8]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies.drop(['color','plot_keywords','director_facebook_likes','actor_1_facebook_likes',
             'actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes',
             'actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link',
             'aspect_ratio'],axis = 1,inplace = True)
movies.shape

(5043, 13)

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [9]:
# Write your code for dropping the rows here
movies= movies.loc[100*(movies.isnull().sum(axis = 1)/len(movies.columns))<= 5.0]
movies.head()

       director_name  num_critic_for_reviews  ...  imdb_score movie_facebook_likes
0      James Cameron                   723.0  ...         7.9                33000
1     Gore Verbinski                   302.0  ...         7.1                    0
2         Sam Mendes                   602.0  ...         6.8                85000
3  Christopher Nolan                   813.0  ...         8.5               164000
5     Andrew Stanton                   462.0  ...         6.6                24000

[5 rows x 13 columns]

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [10]:
# Write your code for dropping the rows here
movies.dropna(thresh = 5)

movies

           director_name  ...  movie_facebook_likes
0          James Cameron  ...                 33000
1         Gore Verbinski  ...                     0
2             Sam Mendes  ...                 85000
3      Christopher Nolan  ...                164000
5         Andrew Stanton  ...                 24000
6              Sam Raimi  ...                     0
7           Nathan Greno  ...                 29000
8            Joss Whedon  ...                118000
9            David Yates  ...                 10000
10           Zack Snyder  ...                197000
11          Bryan Singer  ...                     0
12          Marc Forster  ...                     0
13        Gore Verbinski  ...                  5000
14        Gore Verbinski  ...                 48000
15           Zack Snyder  ...                118000
16        Andrew Adamson  ...                     0
17           Joss Whedon  ...                123000
18          Rob Marshall  ...                 58000
19      Barry Sonnenfeld  ...                 40000
20         Peter Jackson  ...                 65000
21             Marc Webb  ...                 56000
22          Ridley Scott  ...                 17000
23         Peter Jackson  ...                 83000
24           Chris Weitz  ...                     0
25         Peter Jackson  ...                     0
26         James Cameron  ...                 26000
27         Anthony Russo  ...                 72000
28            Peter Berg  ...                 44000
29       Colin Trevorrow  ...                150000
30            Sam Mendes  ...                 80000
...                  ...  ...                   ...
4959     Robert Townsend  ...                   471
4962       Larry Blamire  ...                     0
4964           E.L. Katz  ...                     0
4971      Dennis Iliadis  ...                     0
4973    Darren Aronofsky  ...                 24000
4975     Myles Berkowitz  ...                    30
4977     Morgan Spurlock  ...                     0
4978       Brandon Trost  ...                     0
4979        Joe Swanberg  ...                   812
4984        Edward Burns  ...                   265
4987         Lena Dunham  ...                     0
4997  David Gordon Green  ...                   451
4998        Kevin Jordan  ...                     0
5004          Mike Bruce  ...                    13
5008         Kevin Smith  ...                     0
5009       James Bidgood  ...                    85
5011         Neil LaBute  ...                   489
5012          David Ayer  ...                 10000
5015   Richard Linklater  ...                  2000
5021         Jay Duplass  ...                   297
5023          Daryl Wein  ...                   324
5025         John Waters  ...                     0
5026     Olivier Assayas  ...                   171
5027        Jafar Panahi  ...                   697
5029    Kiyoshi Kurosawa  ...                   817
5033       Shane Carruth  ...                 19000
5034    Neill Dela Llana  ...                    74
5035    Robert Rodriguez  ...                     0
5037        Edward Burns  ...                   413
5042            Jon Gunn  ...                   456

[3884 rows x 13 columns]

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [11]:
# Write your code for filling the NaN values in the 'language' column here
movies['language'] = movies['language'].replace(np.nan, 'English')
movies.shape

(3884, 13)

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [12]:
# Write your code for checking number of retained rows here
length_final_Rows=len(movies.index)
retained_percentage_Rows= (length_final_Rows/length_initial_Rows)*100
print(round(retained_percentage_Rows,2))
#print(length_final_Rows)

77.02

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [13]:
# Write your code for unit conversion here
movies['gross']=(movies['gross'].astype(float)/1000000).round(2)
movies['budget']=(movies['budget'].astype(float)/1000000).round(2)
movies

           director_name  ...  movie_facebook_likes
0          James Cameron  ...                 33000
1         Gore Verbinski  ...                     0
2             Sam Mendes  ...                 85000
3      Christopher Nolan  ...                164000
5         Andrew Stanton  ...                 24000
6              Sam Raimi  ...                     0
7           Nathan Greno  ...                 29000
8            Joss Whedon  ...                118000
9            David Yates  ...                 10000
10           Zack Snyder  ...                197000
11          Bryan Singer  ...                     0
12          Marc Forster  ...                     0
13        Gore Verbinski  ...                  5000
14        Gore Verbinski  ...                 48000
15           Zack Snyder  ...                118000
16        Andrew Adamson  ...                     0
17           Joss Whedon  ...                123000
18          Rob Marshall  ...                 58000
19      Barry Sonnenfeld  ...                 40000
20         Peter Jackson  ...                 65000
21             Marc Webb  ...                 56000
22          Ridley Scott  ...                 17000
23         Peter Jackson  ...                 83000
24           Chris Weitz  ...                     0
25         Peter Jackson  ...                     0
26         James Cameron  ...                 26000
27         Anthony Russo  ...                 72000
28            Peter Berg  ...                 44000
29       Colin Trevorrow  ...                150000
30            Sam Mendes  ...                 80000
...                  ...  ...                   ...
4959     Robert Townsend  ...                   471
4962       Larry Blamire  ...                     0
4964           E.L. Katz  ...                     0
4971      Dennis Iliadis  ...                     0
4973    Darren Aronofsky  ...                 24000
4975     Myles Berkowitz  ...                    30
4977     Morgan Spurlock  ...                     0
4978       Brandon Trost  ...                     0
4979        Joe Swanberg  ...                   812
4984        Edward Burns  ...                   265
4987         Lena Dunham  ...                     0
4997  David Gordon Green  ...                   451
4998        Kevin Jordan  ...                     0
5004          Mike Bruce  ...                    13
5008         Kevin Smith  ...                     0
5009       James Bidgood  ...                    85
5011         Neil LaBute  ...                   489
5012          David Ayer  ...                 10000
5015   Richard Linklater  ...                  2000
5021         Jay Duplass  ...                   297
5023          Daryl Wein  ...                   324
5025         John Waters  ...                     0
5026     Olivier Assayas  ...                   171
5027        Jafar Panahi  ...                   697
5029    Kiyoshi Kurosawa  ...                   817
5033       Shane Carruth  ...                 19000
5034    Neill Dela Llana  ...                    74
5035    Robert Rodriguez  ...                     0
5037        Edward Burns  ...                   413
5042            Jon Gunn  ...                   456

[3884 rows x 13 columns]

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [14]:
# Write your code for creating the profit column here
movies['Profit']=movies['gross']-movies['budget']
movies.tail(5)

         director_name  num_critic_for_reviews  ...  movie_facebook_likes Profit
5033     Shane Carruth                   143.0  ...                 19000   0.41
5034  Neill Dela Llana                    35.0  ...                    74   0.06
5035  Robert Rodriguez                    56.0  ...                     0   2.03
5037      Edward Burns                    14.0  ...                   413  -0.01
5042          Jon Gunn                    43.0  ...                   456   0.09

[5 rows x 14 columns]

In [0]:
# Write your code for sorting the dataframe here
movies.sort_values(('Profit'),axis=0,ascending=False,inplace= True)

In [16]:
top10 = movies.iloc[:10]
top10.head(10)
# Write your code to get the top 10 profiting movies here

          director_name  num_critic_for_reviews  ...  movie_facebook_likes  Profit
0         James Cameron                   723.0  ...                 33000  523.51
29      Colin Trevorrow                   644.0  ...                150000  502.18
26        James Cameron                   315.0  ...                 26000  458.67
3024       George Lucas                   282.0  ...                 33000  449.94
3080   Steven Spielberg                   215.0  ...                 34000  424.45
17          Joss Whedon                   703.0  ...                123000  403.28
794         Joss Whedon                   703.0  ...                123000  403.28
509        Roger Allers                   186.0  ...                 17000  377.78
240        George Lucas                   320.0  ...                 13000  359.54
66    Christopher Nolan                   645.0  ...                 37000  348.32

[10 rows x 14 columns]

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [0]:
# Write your code for dropping duplicate values here
movies.drop_duplicates(['director_name'],keep='first',inplace=True)

In [18]:
# Write code for repeating subtask 2 here
movies['Profit']=movies['gross']-movies['budget']
movies.sort_values(('Profit'),axis=0,ascending=False,inplace= True)
top10 = movies.iloc[:10]
top10.head(10)

          director_name  num_critic_for_reviews  ...  movie_facebook_likes  Profit
0         James Cameron                   723.0  ...                 33000  523.51
29      Colin Trevorrow                   644.0  ...                150000  502.18
3024       George Lucas                   282.0  ...                 33000  449.94
3080   Steven Spielberg                   215.0  ...                 34000  424.45
17          Joss Whedon                   703.0  ...                123000  403.28
509        Roger Allers                   186.0  ...                 17000  377.78
66    Christopher Nolan                   645.0  ...                 37000  348.32
439           Gary Ross                   673.0  ...                140000  330.00
812          Tim Miller                   579.0  ...                117000  305.02
186    Francis Lawrence                   502.0  ...                 82000  294.65

[10 rows x 14 columns]

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [19]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
movies.sort_values(('imdb_score'),axis = 0,ascending=False,inplace = True)
top_imdb_250 = movies.iloc[:250]
top_imdb_250['Rank'] = top_imdb_250['imdb_score'].rank(method='dense', ascending=False)

print(top_imdb_250)
print(top_imdb_250.shape)
print(top_imdb_250['imdb_score'].values)
# Maximum imdb score has same values hence the Ranks is from 1-16 of 250 distinct movies

                         director_name  num_critic_for_reviews  ...  Profit  Rank
3466              Francis Ford Coppola                   208.0  ...  128.82   1.0
66                   Christopher Nolan                   645.0  ...  348.32   2.0
339                      Peter Jackson                   328.0  ...  283.02   3.0
3355                 Quentin Tarantino                   215.0  ...   99.93   3.0
4498                      Sergio Leone                   181.0  ...    4.90   3.0
2051                    Irvin Kershner                   223.0  ...  272.16   4.0
836                    Robert Zemeckis                   149.0  ...  274.69   4.0
3024                      George Lucas                   282.0  ...  449.94   5.0
3867                      Milos Forman                   149.0  ...  107.60   5.0
4747                    Akira Kurosawa                   153.0  ...   -1.73   5.0
3175                         Tony Kaye                   162.0  ...   -0.79   6.0
4427                   Charles Chaplin                   120.0  ...   -1.34   6.0
2158                    Jonathan Demme                   185.0  ...  111.73   6.0
2373                    Hayao Miyazaki                   246.0  ...   -8.95   6.0
4921                      Majid Majidi                    46.0  ...    0.75   7.0
1448                    Roman Polanski                   193.0  ...   -2.48   7.0
712                     Frank Darabont                   186.0  ...   76.80   7.0
4259  Florian Henckel von Donnersmarck                   215.0  ...    9.28   7.0
509                       Roger Allers                   186.0  ...  377.78   7.0
3931                        Ron Fricke                   115.0  ...   -1.40   7.0
4028                   Damien Chazelle                   535.0  ...    9.79   7.0
2242                  Alfred Hitchcock                   290.0  ...   31.19   7.0
1329                    S.S. Rajamouli                    44.0  ...  -11.53   8.0
4105                    Chan-wook Park                   305.0  ...   -0.82   8.0
2606                        Sam Mendes                   176.0  ...  115.06   8.0
4748             Marius A. Markevicius                    26.0  ...   -0.37   8.0
1536                  Richard Marquand                   197.0  ...  276.63   8.0
4659                    Asghar Farhadi                   354.0  ...    6.60   8.0
4286                  Charles Ferguson                    79.0  ...   -0.57   9.0
2223                     Michel Gondry                   273.0  ...   14.13   9.0
...                                ...                     ...  ...     ...   ...
2091                     Jessie Nelson                   129.0  ...   18.27  16.0
4789                        Kay Pollak                    34.0  ...  -24.99  16.0
3038                       Tim Robbins                    77.0  ...   28.02  16.0
1644                  Denis Villeneuve                   478.0  ...   16.88  16.0
1524                        Rob Reiner                    81.0  ...  101.34  16.0
2475                      Greg Mottola                   256.0  ...  101.46  16.0
1648                     Tim McCanlies                    82.0  ...   11.41  16.0
414                Jean-Jacques Annaud                   187.0  ...  -16.60  16.0
3692                   Michael McGowan                    47.0  ...   -5.20  16.0
917                    Terrence Malick                   156.0  ...  -15.61  16.0
115                        Mike Newell                   295.0  ...  139.99  16.0
4046                       John Landis                    94.0  ...  138.60  16.0
4240                       Petter Næss                    67.0  ...  -15.19  16.0
3365                        Don Siegel                    53.0  ...   28.50  16.0
2652                 Denzel Washington                   112.0  ...   15.23  16.0
736                       Michael Mann                   299.0  ...   35.00  16.0
366                        Guy Ritchie                   415.0  ...  119.02  16.0
651                        Chris Wedge                   193.0  ...  117.39  16.0
1593                    John McTiernan                   104.0  ...   92.01  16.0
345                       Rupert Wyatt                   529.0  ...   83.74  16.0
956                     Bennett Miller                   419.0  ...   25.61  16.0
2485                Alejandro Amenábar                   239.0  ...   79.47  16.0
1400                        Tim Burton                   186.0  ...  216.19  16.0
1194                        Peter Berg                   319.0  ...   85.07  16.0
184                       Mark Osborne                   266.0  ...   85.40  16.0
1629                         Ted Demme                   147.0  ...   22.94  16.0
3383                       Mary Harron                   288.0  ...    8.05  16.0
3469                      Jane Campion                    83.0  ...   33.16  16.0
3743                       John Sayles                    68.0  ...    8.27  16.0
4189                        Zach Braff                   205.0  ...   24.28  16.0

[250 rows x 15 columns]
(250, 15)
[9.2 9.  8.9 8.9 8.9 8.8 8.8 8.7 8.7 8.7 8.6 8.6 8.6 8.6 8.5 8.5 8.5 8.5
 8.5 8.5 8.5 8.5 8.4 8.4 8.4 8.4 8.4 8.4 8.3 8.3 8.3 8.3 8.3 8.3 8.3 8.3
 8.3 8.3 8.3 8.3 8.3 8.2 8.2 8.2 8.2 8.2 8.2 8.2 8.2 8.1 8.1 8.1 8.1 8.1
 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1 8.1
 8.1 8.1 8.1 8.1 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.
 8.  8.  8.  8.  8.  8.  8.  8.  8.  7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9
 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.8 7.8 7.8 7.8
 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8
 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8 7.8
 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7
 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7 7.7
 7.7 7.7 7.7 7.7 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6
 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6
 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6 7.6]

In [20]:
Top_Foreign_Lang_Film = top_imdb_250[(top_imdb_250['language'].values != 'English')]
Top_Foreign_Lang_Film

# Write your code to extract top foreign language films from 'IMDb_Top_250' here

                         director_name  num_critic_for_reviews  ...   Profit  Rank
4498                      Sergio Leone                   181.0  ...     4.90   3.0
4747                    Akira Kurosawa                   153.0  ...    -1.73   5.0
2373                    Hayao Miyazaki                   246.0  ...    -8.95   6.0
4921                      Majid Majidi                    46.0  ...     0.75   7.0
4259  Florian Henckel von Donnersmarck                   215.0  ...     9.28   7.0
3931                        Ron Fricke                   115.0  ...    -1.40   7.0
1329                    S.S. Rajamouli                    44.0  ...   -11.53   8.0
4105                    Chan-wook Park                   305.0  ...    -0.82   8.0
4659                    Asghar Farhadi                   354.0  ...     6.60   8.0
2734                        Fritz Lang                   260.0  ...    -5.97   9.0
2829               Oliver Hirschbiegel                   192.0  ...    -8.00   9.0
4000              Juan José Campanella                   262.0  ...    18.17  10.0
4585                Joshua Oppenheimer                   248.0  ...    -0.52  10.0
2914                       Je-kyu Kang                    86.0  ...   -11.69  11.0
3553                      José Padilha                   142.0  ...    -3.99  11.0
4461                 Thomas Vinterberg                    98.0  ...     0.35  11.0
3423                   Katsuhiro Ôtomo                   150.0  ... -1099.56  11.0
3456                 Vincent Paronnaud                   242.0  ...    -2.86  12.0
4284                        Ari Folman                   231.0  ...     0.78  12.0
3344                       Karan Johar                   210.0  ...    -7.98  12.0
4144                     Walter Salles                    71.0  ...     2.70  12.0
2919                   Stéphane Aubier                    99.0  ...    -9.53  13.0
2605                           Ang Lee                   287.0  ...   113.07  13.0
3264                    Michael Haneke                   447.0  ...    -8.67  13.0
3510                       Yash Chopra                    29.0  ...    -4.08  13.0
4415                  Fabián Bielinsky                    94.0  ...    -0.28  13.0
4499                     Anna Muylaert                   111.0  ...    -3.62  13.0
4640                   Cristian Mungiu                   233.0  ...     0.60  13.0
2493                       Yimou Zhang                   283.0  ...   -30.92  13.0
3677              Christophe Barratier                   112.0  ...    -1.87  13.0
2256                      Stephen Chow                   377.0  ...    -2.90  14.0
4375                        Tom Tykwer                   181.0  ...     3.77  14.0
1236                        Mel Gibson                   283.0  ...    10.86  14.0
3856                     Mike van Diem                    54.0  ...    -3.79  14.0
4385                      Ritesh Batra                   195.0  ...     3.23  14.0
2119                  Christian Carion                   115.0  ...   -20.95  14.0
504                     Jacques Perrin                   113.0  ...   -20.59  14.0
4263                    Sylvain Chomet                   167.0  ...    -2.50  14.0
2992                  Paolo Sorrentino                   280.0  ...    -6.36  15.0
3576                   Wolfgang Becker                   153.0  ...    -0.74  15.0
3943              Jorge Ramírez Suárez                    26.0  ...    -3.90  15.0
3949           Fernando León de Aranoa                    64.0  ...    -3.85  15.0
3178                   François Girard                    94.0  ...    -0.53  15.0
3759                      Denys Arcand                   135.0  ...    -2.57  15.0
3009                          Chuan Lu                   149.0  ...   -11.88  15.0
3705                    Eugenio Derbez                    41.0  ...    39.46  16.0
4024                       Luc Jacquet                   169.0  ...    69.41  16.0
4523                      Gareth Evans                   481.0  ...     3.01  16.0
4255                    Chia-Liang Liu                    77.0  ...     9.55  16.0
4789                        Kay Pollak                    34.0  ...   -24.99  16.0
4240                       Petter Næss                    67.0  ...   -15.19  16.0

[51 rows x 15 columns]

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [21]:
# Write your code for extracting the top 10 directors here
ds = movies.groupby(['director_name','movie_title'])[['imdb_score']].mean()
ds.sort_values(("imdb_score"),axis = 0,ascending=False,inplace = True)
top10director = ds.iloc[:10]
top10director

                                                                      imdb_score
director_name        movie_title
Francis Ford Coppola The Godfather                                           9.2
Christopher Nolan    The Dark Knight                                         9.0
Peter Jackson        The Lord of the Rings: The Return of the King           8.9
Sergio Leone         The Good, the Bad and the Ugly                          8.9
Quentin Tarantino    Pulp Fiction                                            8.9
Robert Zemeckis      Forrest Gump                                            8.8
Irvin Kershner       Star Wars: Episode V - The Empire Strikes Back          8.8
Milos Forman         One Flew Over the Cuckoo's Nest                         8.7
George Lucas         Star Wars: Episode IV - A New Hope                      8.7
Akira Kurosawa       Seven Samurai                                           8.7

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [0]:
# Write your code for extracting the first two genres of each movie here
top_imdb_250.loc[top_imdb_250.index[0], 'genre_1'] = movies['genres'].iloc[0]
top_imdb_250.loc[top_imdb_250.index[0], 'genre_2'] = movies['genres'].iloc[1]

In [39]:
movies_by_segment = top_imdb_250[['genre_1','genre_2']]
movies_by_segment

# Write your code for grouping the dataframe here

          genre_1                      genre_2
3466  Crime|Drama  Action|Crime|Drama|Thriller
66            NaN                          NaN
339           NaN                          NaN
3355          NaN                          NaN
4498          NaN                          NaN
2051          NaN                          NaN
836           NaN                          NaN
3024          NaN                          NaN
3867          NaN                          NaN
4747          NaN                          NaN
3175          NaN                          NaN
4427          NaN                          NaN
2158          NaN                          NaN
2373          NaN                          NaN
4921          NaN                          NaN
1448          NaN                          NaN
712           NaN                          NaN
4259          NaN                          NaN
509           NaN                          NaN
3931          NaN                          NaN
4028          NaN                          NaN
2242          NaN                          NaN
1329          NaN                          NaN
4105          NaN                          NaN
2606          NaN                          NaN
4748          NaN                          NaN
1536          NaN                          NaN
4659          NaN                          NaN
4286          NaN                          NaN
2223          NaN                          NaN
...           ...                          ...
2091          NaN                          NaN
4789          NaN                          NaN
3038          NaN                          NaN
1644          NaN                          NaN
1524          NaN                          NaN
2475          NaN                          NaN
1648          NaN                          NaN
414           NaN                          NaN
3692          NaN                          NaN
917           NaN                          NaN
115           NaN                          NaN
4046          NaN                          NaN
4240          NaN                          NaN
3365          NaN                          NaN
2652          NaN                          NaN
736           NaN                          NaN
366           NaN                          NaN
651           NaN                          NaN
1593          NaN                          NaN
345           NaN                          NaN
956           NaN                          NaN
2485          NaN                          NaN
1400          NaN                          NaN
1194          NaN                          NaN
184           NaN                          NaN
1629          NaN                          NaN
3383          NaN                          NaN
3469          NaN                          NaN
3743          NaN                          NaN
4189          NaN                          NaN

[250 rows x 2 columns]

In [24]:
PopGenre = movies.groupby("genres")[['gross']].mean()
PopGenre.sort_values(('gross'),axis = 0,ascending = False,inplace =True)
PopGenre
# Write your code for getting the 5 most popular combo of genres here

                                                         gross
genres
Family|Sci-Fi                                       434.950000
Adventure|Sci-Fi|Thriller                           424.650000
Adventure|Animation|Drama|Family|Musical            422.780000
Action|Adventure|Fantasy|Romance                    403.710000
Animation|Comedy|Family|Sci-Fi                      368.050000
Adventure|Animation|Comedy|Drama|Family|Fantasy     356.450000
Action|Biography|Drama|History|Thriller|War         350.120000
Adventure|Drama|Sci-Fi|Thriller                     341.040000
Action|Adventure|Fantasy|Sci-Fi                     305.735000
Adventure|Drama|Fantasy|Romance                     296.480000
Adventure|Family|Fantasy|Mystery                    290.995000
Action|Adventure|Animation|Family                   261.440000
Action|Adventure|Comedy|Family|Fantasy              250.860000
Adventure|Comedy|Family|Mystery|Sci-Fi              250.150000
Adventure|Animation|Comedy|Family|Fantasy|Romance   243.310000
Action|Animation|Comedy|Family|Sci-Fi               242.185000
Action|Adventure|Family|Fantasy|Romance             241.410000
Action|Adventure|Sci-Fi                             238.783077
Adventure|Drama|Sci-Fi                              228.430000
Action|Adventure|Animation|Comedy|Family|Fantasy    226.545000
Action|Adventure|Animation|Comedy|Drama|Family|...  222.490000
Adventure|Drama|Family|Fantasy                      222.440000
Adventure|Animation|Comedy|Family|Fantasy|Musical   220.070000
Animation|Comedy|Family|Fantasy|Music               218.470000
Drama|Fantasy|Romance|Thriller                      217.630000
Adventure|Animation|Comedy|Family|Fantasy|Music...  209.080000
Action|Adventure|Crime|Mystery|Thriller             209.020000
Action|Adventure|Fantasy|Thriller                   202.010000
Drama|Family|Fantasy|Romance                        201.150000
Drama|History|Romance|War                           198.660000
...                                                        ...
Comedy|Drama|Musical                                  0.110000
Romance                                               0.105000
Crime|Drama|Mystery|Romance                           0.090000
Drama|Romance|Sci-Fi|Thriller                         0.080000
Animation|Comedy|Crime|Drama|Family                   0.070000
Fantasy|Horror|Mystery                                0.070000
Action|Adventure|Drama|History                        0.070000
Comedy|Crime|Drama|Horror|Thriller                    0.060000
Action|Animation|Sci-Fi|Thriller                      0.060000
Thriller                                              0.040000
Adventure|Comedy|Horror                               0.040000
Action|Comedy|Drama|Thriller                          0.030000
Action|Drama|History|War                              0.030000
Comedy|Horror|Musical                                 0.030000
Drama|Fantasy|Sci-Fi                                  0.020000
Action|Biography|Documentary|Sport                    0.020000
Drama|Fantasy|Mystery|Romance                         0.020000
Comedy|Drama|Fantasy|Music|Romance                    0.020000
Mystery|Romance|Thriller                              0.020000
Sci-Fi                                                0.020000
Comedy|Fantasy|Horror|Musical                         0.010000
Adventure|War|Western                                 0.010000
Comedy|Fantasy|Thriller                               0.010000
Crime|Drama|Film-Noir|Mystery|Thriller                0.010000
Comedy|Drama|Sci-Fi                                   0.010000
Comedy|Fantasy|Musical|Sci-Fi                         0.000000
Adventure|Documentary                                 0.000000
Comedy|Horror                                         0.000000
Crime|Documentary                                     0.000000
Adventure|Family|Fantasy                              0.000000

[518 rows x 1 columns]

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [0]:
# Include all movies in which Brad_Pitt is the lead
Brad_Pitt = movies.loc[movies['actor_1_name'] == 'Brad Pitt']

In [0]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies.loc[movies['actor_1_name'] == 'Meryl Streep']

# Include all movies in which Meryl_Streep is the lead

In [0]:
Leo_Caprio = movies.loc[movies['actor_1_name'] == 'Leonardo DiCaprio']

# Include all movies in which Leo_Caprio is the lead

In [33]:
# Write your code for combining the three dataframes here
combined = Brad_Pitt.append([Leo_Caprio, Meryl_Streep])
combined

              director_name  ...  Profit
792         Patrick Gilmore  ...  -33.71
255              Doug Liman  ...   66.34
2682         Andrew Dominik  ...   -0.06
452         Martin Scorsese  ...   47.97
179   Alejandro G. Iñárritu  ...   48.64
50             Baz Luhrmann  ...   39.81
2067             Jerry Zaks  ...  -10.22
1204            Nora Ephron  ...   54.13
1408          David Frankel  ...   89.73

[9 rows x 14 columns]

In [0]:
# Write your code for grouping the combined dataframe & finding the mean of critic reviews and audience reviews here
superstar= combined.groupby('actor_1_name')[['num_critic_for_reviews','num_user_for_reviews']].mean()
superstar.sort_values(('num_critic_for_reviews'),axis = 0,ascending = False,inplace =True)

In [35]:
superstar

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Leonardo DiCaprio              395.250000            744.000000
Brad Pitt                      248.333333            419.333333
Meryl Streep                   230.000000            454.000000

**Checkpoint 6:** `Leonardo` has aced both the lists!